# Start with the specified PyTorch image
# FROM nvcr.io/nvidia/pytorch:21.10-py3 # Tesla V
FROM nvcr.io/nvidia/pytorch:23.04-py3

# Set debconf to run non-interactively and preconfigure the tzdata package
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "tzdata tzdata/Areas select Asia" | debconf-set-selections && \
    echo "tzdata tzdata/Zones/Asia select Seoul" | debconf-set-selections

# Update the package list and install specified packages
RUN apt-get update && \
    apt-get install -y \
    ffmpeg \
    libsm6 \
    libxext6 \
    # rm -rf /var/lib/apt/lists/* \
    rm -r /opt/conda/lib/python3.8/site-packages/cv2

# Install the specified pip packages
RUN pip install \
    opencv-python==4.7.0.72 \
    supervision==0.6.0 \
    thop \
    pandas \
    timm \
    pycuda

